tasks:
  - id: "hello"
    type: "printer"
    outputs:
      flag: "sai1"
    parameters:
      text: "Hello,"
  - id: "world"
    type: "printer"
    inputs:
      flag: "sai1"
    parameters:
      text: "World!"
